Deer: 1
Boar: 1
Neck: 1
Greyling: 1
Eikthyr: 10
Greydwarf: 2
Greydwarf_Shaman: 2
Greydwarf_Elite: 3
Ghost: 3
Skeleton: 1
Troll: 10
gd_king: 10
Leech: 2
Blob: 2
Draugr: 2
Draugr_Ranged: 2
Draugr_Elite: 4
BlobElite: 4
Wraith: 4
Abomination: 20
Bonemass: 30
Wolf: 2
Fenring: 4
Fenring_Cultist: 5
Ulv: 4
Hatchling: 3
StoneGolem: 30
Fenring_Cultist_Hildir: 20
Skeleton_Hildir: 20
GoblinShaman_Hildir: 30
GoblinBrute_Hildir: 30
Dragon: 40
Goblin: 5
BlobTar: 10
Lox: 6
Serpent: 30
GoblinKing: 60
Seeker: 10
SeekerBrute: 15
SeekerBrood: 6
Hare: 6
Tick: 6
Gjall: 20
Dverger: 20
DvergerArbalest: 20
DvergerMage: 20
DvergerMageFire: 20
DvergerMageIce: 20
DvergerMageSupport: 20
SeekerQueen: 100
Surtling: 3
